events {
    worker_connections 1024;
}

http {
    upstream nextjs_apps {
        server project-one:3000;
        server project-two:3000;
        server project-three:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://nextjs_apps;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}